export const industries = [
  {
    name: "Healthcare",
    items: [
      "Telemedicine Platforms",
      "Electronic Health Records (EHR)",
      "Patient Management Systems",
      "Appointment Scheduling Software",
      "Healthcare Analytics Platforms",
      "Wellness Tracking Applications",
      "Medical Device Integration",
      "Hospital Management Systems",
    ],
  },
  {
    name: "Fintech",
    items: [
      "Digital Payment Platforms",
      "Mobile Banking Applications",
      "Cryptocurrency Wallets",
      "Peer-to-Peer Payment Systems",
      "Lending Management Software",
      "Credit Scoring Systems",
      "Financial Analytics Tools",
      "Blockchain Payment Solutions",
      "Trading Platform Development",
    ],
  },
  {
    name: "Logistics",
    items: [
      "Delivery Management Systems",
      "Shipping Logistics Management",
      "Fleet Management Software",
      "Inventory Management Software",
      "Telematics Software Development",
      "Warehouse Management Systems",
      "Route Optimization Platforms",
      "Supply Chain Visibility Tools",
      "Last-Mile Delivery Solutions",
    ],
  },
  {
    name: "Retail",
    items: [
      "Point-of-Sale (POS) Systems",
      "Inventory Management Platforms",
      "Customer Loyalty Programs",
      "Staff Management Software",
      "Omnichannel Retail Solutions",
      "Price Management Systems",
      "Retail Analytics Dashboards",
      "Store Operations Management",
      "Customer Relationship Management",
    ],
  },
  {
    name: "Ecommerce",
    items: [
      "Multi-Vendor Marketplaces",
      "B2B Ecommerce Platforms",
      "B2C Online Stores",
      "Shopping Cart Development",
      "Payment Gateway Integration",
      "Product Recommendation Engines",
      "Order Management Systems",
      "Customer Review Platforms",
      "Auction & Bidding Systems",
    ],
  },
  {
    name: "Education",
    items: [
      "Learning Management Systems (LMS)",
      "Online Course Platforms",
      "Virtual Classroom Software",
      "Student Information Systems",
      "Assessment & Testing Platforms",
      "Educational Content Management",
      "VR Learning Applications",
      "AI-Powered Tutoring Systems",
      "Certification Management",
    ],
  },
  {
    name: "BFSI Solutions",
    items: [
      "Core Banking Systems",
      "Insurance Management Platforms",
      "Loan Origination Systems",
      "Credit Monitoring Software",
      "Regulatory Compliance Tools",
      "Risk Management Systems",
      "Customer Onboarding Solutions",
      "Anti-Money Laundering (AML) Tools",
      "Investment Portfolio Management",
    ],
  },
  {
    name: "Sports & Gaming",
    items: [
      "Fantasy Sports Platforms",
      "Gaming Applications",
      "Tournament Management Systems",
      "Live Streaming Applications",
      "Sports Analytics Platforms",
      "Community Gaming Solutions",
      "Leaderboard Systems",
      "In-Game Payment Solutions",
      "Sports Betting Platforms",
    ],
  },
  {
    name: "Energy & Utility",
    items: [
      "Smart Grid Management",
      "Energy Monitoring Systems",
      "Utility Billing Platforms",
      "Renewable Energy Management",
      "Consumption Analytics Tools",
      "IoT Sensor Integration",
      "Energy Trading Platforms",
      "Grid Optimization Software",
      "Meter Data Management",
    ],
  },
  {
    name: "Real Estate",
    items: [
      "Property Management Systems",
      "Virtual Tour Platforms",
      "Real Estate CRM Solutions",
      "Rental Management Applications",
      "Property Listing Websites",
      "Automated Valuation Models",
      "Property Investment Platforms",
      "Facility Management Software",
      "Real Estate Analytics Tools",
    ],
  },
  {
    name: "Media & Entertainment",
    items: [
      "Content Management Systems",
      "Streaming Platforms",
      "Digital Asset Management",
      "Social Media Applications",
      "Video Processing Tools",
      "AI Content Creation Platforms",
      "Live Broadcasting Solutions",
      "Creative Collaboration Tools",
      "Subscription Management Systems",
    ],
  },
  {
    name: "SaaS Products",
    items: [
      "Multi-Tenant Applications",
      "Subscription Management Systems",
      "Cloud-Native Platforms",
      "API Development & Integration",
      "Analytics Dashboard Solutions",
      "Customer Success Platforms",
      "Workflow Automation Tools",
      "Data Management Systems",
      "Enterprise Software Solutions",
    ],
  },
  {
    name: "Automotive",
    items: [
      "Dealership Management Systems",
      "Vehicle Valuation Tools",
      "Service Scheduling Platforms",
      "Car Rental Management",
      "Fleet Tracking Systems",
      "Automotive CRM Solutions",
      "Parts Inventory Management",
      "Customer Engagement Platforms",
      "Vehicle Financing Calculators",
    ],
  },
  {
    name: "Food & Beverage",
    items: [
      "Food Delivery Platforms",
      "Restaurant Management Systems",
      "Kitchen Display Systems",
      "Menu Management Software",
      "Food Safety Compliance Tools",
      "Inventory Tracking Systems",
      "Customer Ordering Apps",
      "Multi-Vendor Food Marketplaces",
      "Recipe Management Systems",
    ],
  },
  {
    name: "Legal & Professional Services",
    items: [
      "Case Management Systems",
      "Document Automation Tools",
      "Legal Practice Management",
      "Time & Billing Software",
      "Client Portal Systems",
      "Contract Management Solutions",
      "Compliance Tracking Tools",
      "Legal Research Platforms",
      "Court Filing Systems",
    ],
  },
  {
    name: "Human Resources",
    items: [
      "Applicant Tracking Systems",
      "Employee Onboarding Platforms",
      "Performance Management Tools",
      "Payroll Management Systems",
      "Workforce Analytics Solutions",
      "Employee Self-Service Portals",
      "Talent Acquisition Platforms",
      "HR Compliance Software",
      "Learning & Development Systems",
    ],
  },
  {
    name: "Insurance",
    items: [
      "Policy Management Systems",
      "Claims Processing Automation",
      "Insurance CRM Solutions",
      "Premium Calculation Tools",
      "Underwriting Software",
      "Customer Self-Service Portals",
      "Insurance Mobile Applications",
      "Risk Assessment Tools",
      "Regulatory Reporting Systems",
    ],
  },
  {
    name: "Social Commerce",
    items: [
      "Social Media Platforms",
      "Peer-to-Peer Marketplaces",
      "Community Management Systems",
      "Social Shopping Applications",
      "Influencer Marketing Platforms",
      "User-Generated Content Systems",
      "Social Analytics Tools",
      "Crypto Wallet Integration",
      "Social Gaming Features",
    ],
  },
  {
    name: "Manufacturing & B2B",
    items: [
      "Supply Chain Management",
      "Vendor Management Platforms",
      "Procurement Automation Systems",
      "Manufacturing Execution Systems",
      "Quality Management Software",
      "Business Intelligence Dashboards",
      "B2B Marketplace Development",
      "Production Planning Tools",
      "Equipment Maintenance Systems",
    ],
  },
];
