// Rewrites src/assets/original/*.{png,jpg,jpeg} into WebP next to the source and
// generates src/assets/images.ts, which pairs each image URL with its intrinsic
// width/height. Components spread those onto <img> so nothing shifts on load.
//
// Run after adding or replacing any image: npm run images
import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, parse } from "node:path";
import sharp from "sharp";

const DIR = "src/assets/original";
// Cards render at most ~620 CSS px wide, so 1240 covers 2x. The sources are 3924px.
const MAX_WIDTH = 1240;
const QUALITY = 78;

const files = (await readdir(DIR)).filter((f) => /\.(png|jpe?g)$/i.test(f));
const sizes = {};
let before = 0;
let after = 0;

for (const file of files) {
  const src = join(DIR, file);
  const srcBytes = (await stat(src)).size;
  before += srcBytes;

  const image = sharp(await readFile(src));
  const { width = 0, height = 0 } = await image.metadata();
  const scale = width > MAX_WIDTH ? MAX_WIDTH / width : 1;
  const outWidth = Math.round(width * scale);
  const outHeight = Math.round(height * scale);

  const buffer = await image
    .resize(scale < 1 ? { width: MAX_WIDTH } : undefined)
    .webp({ quality: QUALITY, effort: 6 })
    .toBuffer();

  // Flat-colour logos and line art come out larger as WebP than as source PNG.
  // Keep whichever is smaller so no image ever regresses.
  const keepWebp = buffer.length < srcBytes;
  const name = keepWebp ? `${parse(file).name}.webp` : file;
  if (keepWebp) await writeFile(join(DIR, name), buffer);
  after += keepWebp ? buffer.length : srcBytes;

  sizes[name] = keepWebp ? { width: outWidth, height: outHeight } : { width, height };
  const kb = (bytes) => Math.round(bytes / 1024);
  console.log(
    `${file} ${width}x${height} ${kb(srcBytes)}KB -> ${name} ` +
      `${keepWebp ? `${outWidth}x${outHeight} ${kb(buffer.length)}KB` : "kept as source"}`,
  );
}

const ident = (name) => parse(name).name.replace(/[^a-z0-9]+(.)/gi, (_, c) => c.toUpperCase());
const entries = Object.entries(sizes).sort(([a], [b]) => a.localeCompare(b));

await writeFile(
  "src/assets/images.ts",
  [
    "// Generated by scripts/optimize-images.mjs. Do not edit by hand; run `npm run images`.",
    ...entries.map(([name]) => `import ${ident(name)} from "./original/${name}";`),
    "",
    "export const images = {",
    ...entries.map(
      ([name, { width, height }]) =>
        `  "${parse(name).name}": { src: ${ident(name)}, width: ${width}, height: ${height} },`,
    ),
    "} as const;",
    "",
    "export type SiteImage = (typeof images)[keyof typeof images];",
    "",
  ].join("\n"),
);

console.log(
  `\n${files.length} images: ${(before / 1048576).toFixed(1)}MB -> ${(after / 1048576).toFixed(1)}MB`,
);
