// Generated by scripts/optimize-images.mjs. Do not edit by hand; run `npm run images`.
import about from "./original/about.webp";
import footer from "./original/footer.png";
import founder from "./original/founder.webp";
import projectCarService from "./original/project-car-service.webp";
import projectCar from "./original/project-car.webp";
import projectCma from "./original/project-cma.webp";
import projectGifting from "./original/project-gifting.webp";
import projectGrocery from "./original/project-grocery.webp";
import projectInsurance from "./original/project-insurance.webp";
import projectInvestigation from "./original/project-investigation.webp";
import projectLms from "./original/project-lms.webp";
import projectLuxury from "./original/project-luxury.webp";
import projectManagement from "./original/project-management.webp";
import projectMarketplace from "./original/project-marketplace.webp";
import projectPayment from "./original/project-payment.webp";
import projectRecruitment from "./original/project-recruitment.webp";
import projectSocial from "./original/project-social.webp";
import projectStoryboard from "./original/project-storyboard.webp";
import projectSukoon from "./original/project-sukoon.webp";
import serviceAi from "./original/service-ai.webp";
import serviceCloud from "./original/service-cloud.png";
import serviceCommerce from "./original/service-commerce.png";
import serviceWeb from "./original/service-web.webp";
import techElastic from "./original/tech-elastic.png";
import techHuggingface from "./original/tech-huggingface.png";
import techKafka from "./original/tech-kafka.png";
import techLangchain from "./original/tech-langchain.png";
import techOpenai from "./original/tech-openai.png";
import techPinecone from "./original/tech-pinecone.png";
import techPython from "./original/tech-python.webp";
import techTensorflow from "./original/tech-tensorflow.png";

export const images = {
  about: { src: about, width: 533, height: 403 },
  footer: { src: footer, width: 1344, height: 420 },
  founder: { src: founder, width: 895, height: 980 },
  "project-car-service": { src: projectCarService, width: 1240, height: 1106 },
  "project-car": { src: projectCar, width: 1240, height: 1106 },
  "project-cma": { src: projectCma, width: 1240, height: 1106 },
  "project-gifting": { src: projectGifting, width: 1240, height: 1106 },
  "project-grocery": { src: projectGrocery, width: 1240, height: 931 },
  "project-insurance": { src: projectInsurance, width: 1240, height: 827 },
  "project-investigation": { src: projectInvestigation, width: 1240, height: 697 },
  "project-lms": { src: projectLms, width: 1240, height: 1106 },
  "project-luxury": { src: projectLuxury, width: 948, height: 950 },
  "project-management": { src: projectManagement, width: 1240, height: 930 },
  "project-marketplace": { src: projectMarketplace, width: 1240, height: 1240 },
  "project-payment": { src: projectPayment, width: 1240, height: 1084 },
  "project-recruitment": { src: projectRecruitment, width: 1240, height: 835 },
  "project-social": { src: projectSocial, width: 1240, height: 1106 },
  "project-storyboard": { src: projectStoryboard, width: 1240, height: 1106 },
  "project-sukoon": { src: projectSukoon, width: 1240, height: 1106 },
  "service-ai": { src: serviceAi, width: 937, height: 400 },
  "service-cloud": { src: serviceCloud, width: 1114, height: 424 },
  "service-commerce": { src: serviceCommerce, width: 512, height: 400 },
  "service-web": { src: serviceWeb, width: 422, height: 400 },
  "tech-elastic": { src: techElastic, width: 148, height: 148 },
  "tech-huggingface": { src: techHuggingface, width: 148, height: 148 },
  "tech-kafka": { src: techKafka, width: 148, height: 148 },
  "tech-langchain": { src: techLangchain, width: 148, height: 148 },
  "tech-openai": { src: techOpenai, width: 148, height: 148 },
  "tech-pinecone": { src: techPinecone, width: 148, height: 148 },
  "tech-python": { src: techPython, width: 148, height: 149 },
  "tech-tensorflow": { src: techTensorflow, width: 148, height: 149 },
} as const;

export type SiteImage = (typeof images)[keyof typeof images];
