/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AiDevAutomationPlaybookRouteImport } from './routes/ai-dev-automation-playbook'
import { Route as AiDevAutomationPlaybookFormRouteImport } from './routes/ai-dev-automation-playbook-form'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as InsideProjectRouteImport } from './routes/inside-project'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDevAutomationPlaybookRoute = AiDevAutomationPlaybookRouteImport.update({
  id: '/ai-dev-automation-playbook',
  path: '/ai-dev-automation-playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDevAutomationPlaybookFormRoute =
  AiDevAutomationPlaybookFormRouteImport.update({
    id: '/ai-dev-automation-playbook-form',
    path: '/ai-dev-automation-playbook-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const InsideProjectRoute = InsideProjectRouteImport.update({
  id: '/inside-project',
  path: '/inside-project',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-dev-automation-playbook': typeof AiDevAutomationPlaybookRoute
  '/ai-dev-automation-playbook-form': typeof AiDevAutomationPlaybookFormRoute
  '/blogs': typeof BlogsRoute
  '/contact-us': typeof ContactUsRoute
  '/inside-project': typeof InsideProjectRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-dev-automation-playbook': typeof AiDevAutomationPlaybookRoute
  '/ai-dev-automation-playbook-form': typeof AiDevAutomationPlaybookFormRoute
  '/blogs': typeof BlogsRoute
  '/contact-us': typeof ContactUsRoute
  '/inside-project': typeof InsideProjectRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-dev-automation-playbook': typeof AiDevAutomationPlaybookRoute
  '/ai-dev-automation-playbook-form': typeof AiDevAutomationPlaybookFormRoute
  '/blogs': typeof BlogsRoute
  '/contact-us': typeof ContactUsRoute
  '/inside-project': typeof InsideProjectRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/ai-dev-automation-playbook'
    | '/ai-dev-automation-playbook-form'
    | '/blogs'
    | '/contact-us'
    | '/inside-project'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/ai-dev-automation-playbook'
    | '/ai-dev-automation-playbook-form'
    | '/blogs'
    | '/contact-us'
    | '/inside-project'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/ai-dev-automation-playbook'
    | '/ai-dev-automation-playbook-form'
    | '/blogs'
    | '/contact-us'
    | '/inside-project'
    | '/privacy-policy'
    | '/projects'
    | '/services'
    | '/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AiDevAutomationPlaybookRoute: typeof AiDevAutomationPlaybookRoute
  AiDevAutomationPlaybookFormRoute: typeof AiDevAutomationPlaybookFormRoute
  BlogsRoute: typeof BlogsRoute
  ContactUsRoute: typeof ContactUsRoute
  InsideProjectRoute: typeof InsideProjectRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-dev-automation-playbook': {
      id: '/ai-dev-automation-playbook'
      path: '/ai-dev-automation-playbook'
      fullPath: '/ai-dev-automation-playbook'
      preLoaderRoute: typeof AiDevAutomationPlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-dev-automation-playbook-form': {
      id: '/ai-dev-automation-playbook-form'
      path: '/ai-dev-automation-playbook-form'
      fullPath: '/ai-dev-automation-playbook-form'
      preLoaderRoute: typeof AiDevAutomationPlaybookFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inside-project': {
      id: '/inside-project'
      path: '/inside-project'
      fullPath: '/inside-project'
      preLoaderRoute: typeof InsideProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AiDevAutomationPlaybookRoute: AiDevAutomationPlaybookRoute,
  AiDevAutomationPlaybookFormRoute: AiDevAutomationPlaybookFormRoute,
  BlogsRoute: BlogsRoute,
  ContactUsRoute: ContactUsRoute,
  InsideProjectRoute: InsideProjectRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
